# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

version: "2"

linters:
  settings:
    govet:
      disable:
        - printf
  exclusions:
    paths-except:
      - internal/driver
