// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: common/annotation.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Options struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否跳过鉴权
	SkipAuth bool `protobuf:"varint,6,opt,name=skip_auth,json=skipAuth,proto3" json:"skip_auth,omitempty"`
	// 请求日志字段掩码
	ReqMaskPaths []string `protobuf:"bytes,11,rep,name=req_mask_paths,json=reqMaskPaths,proto3" json:"req_mask_paths,omitempty"`
	// 响应日志字段掩码
	RespMaskPaths []string `protobuf:"bytes,12,rep,name=resp_mask_paths,json=respMaskPaths,proto3" json:"resp_mask_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_common_annotation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_common_annotation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_common_annotation_proto_rawDescGZIP(), []int{0}
}

func (x *Options) GetSkipAuth() bool {
	if x != nil {
		return x.SkipAuth
	}
	return false
}

func (x *Options) GetReqMaskPaths() []string {
	if x != nil {
		return x.ReqMaskPaths
	}
	return nil
}

func (x *Options) GetRespMaskPaths() []string {
	if x != nil {
		return x.RespMaskPaths
	}
	return nil
}

var file_common_annotation_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Options)(nil),
		Field:         202403216,
		Name:          "api.common.options",
		Tag:           "bytes,202403216,opt,name=options",
		Filename:      "common/annotation.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional api.common.Options options = 202403216;
	E_Options = &file_common_annotation_proto_extTypes[0]
)

var File_common_annotation_proto protoreflect.FileDescriptor

const file_common_annotation_proto_rawDesc = "" +
	"\n" +
	"\x17common/annotation.proto\x12\n" +
	"api.common\x1a google/protobuf/descriptor.proto\"t\n" +
	"\aOptions\x12\x1b\n" +
	"\tskip_auth\x18\x06 \x01(\bR\bskipAuth\x12$\n" +
	"\x0ereq_mask_paths\x18\v \x03(\tR\freqMaskPaths\x12&\n" +
	"\x0fresp_mask_paths\x18\f \x03(\tR\rrespMaskPaths:P\n" +
	"\aoptions\x12\x1e.google.protobuf.MethodOptions\x18\x90\xdb\xc1` \x01(\v2\x13.api.common.OptionsR\aoptionsB4Z2github.com/starudream/go-lib/example/v2/api/commonb\x06proto3"

var (
	file_common_annotation_proto_rawDescOnce sync.Once
	file_common_annotation_proto_rawDescData []byte
)

func file_common_annotation_proto_rawDescGZIP() []byte {
	file_common_annotation_proto_rawDescOnce.Do(func() {
		file_common_annotation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_annotation_proto_rawDesc), len(file_common_annotation_proto_rawDesc)))
	})
	return file_common_annotation_proto_rawDescData
}

var file_common_annotation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_annotation_proto_goTypes = []any{
	(*Options)(nil),                    // 0: api.common.Options
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_common_annotation_proto_depIdxs = []int32{
	1, // 0: api.common.options:extendee -> google.protobuf.MethodOptions
	0, // 1: api.common.options:type_name -> api.common.Options
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_annotation_proto_init() }
func file_common_annotation_proto_init() {
	if File_common_annotation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_annotation_proto_rawDesc), len(file_common_annotation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_common_annotation_proto_goTypes,
		DependencyIndexes: file_common_annotation_proto_depIdxs,
		MessageInfos:      file_common_annotation_proto_msgTypes,
		ExtensionInfos:    file_common_annotation_proto_extTypes,
	}.Build()
	File_common_annotation_proto = out.File
	file_common_annotation_proto_goTypes = nil
	file_common_annotation_proto_depIdxs = nil
}
