// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: admin/user_service.proto

package admin

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	user "github.com/starudream/go-lib/example/v2/api/admin/user"
	common "github.com/starudream/go-lib/example/v2/api/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_admin_user_service_proto protoreflect.FileDescriptor

const file_admin_user_service_proto_rawDesc = "" +
	"\n" +
	"\x18admin/user_service.proto\x12\tapi.admin\x1a\x15admin/user/user.proto\x1a\x17common/annotation.proto\x1a\x13common/common.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xf5\x02\n" +
	"\x10AdminUserService\x12q\n" +
	"\x06Health\x12\x16.google.protobuf.Empty\x1a\x17.google.protobuf.Struct\"6\x92A\x10\n" +
	"\f健康检查b\x00\x82\xd3\xe4\x93\x02\x15\x12\x13/admin/user/_health\x82ٍ\x84\x06\x020\x01\x12s\n" +
	"\aAddUser\x12\x1a.api.admin.user.AddUserReq\x1a\x0e.api.common.Id\"<\x92A\x0f\n" +
	"\r用户|创建\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/admin/user/add\x82ٍ\x84\x06\n" +
	"Z\bpassword\x12y\n" +
	"\aGetUser\x12\x1a.api.admin.user.GetUserReq\x1a\x14.api.admin.user.User\"<\x92A\x0f\n" +
	"\r用户|获取\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/admin/user/get\x82ٍ\x84\x06\n" +
	"b\bpasswordB3Z1github.com/starudream/go-lib/example/v2/api/adminb\x06proto3"

var file_admin_user_service_proto_goTypes = []any{
	(*emptypb.Empty)(nil),   // 0: google.protobuf.Empty
	(*user.AddUserReq)(nil), // 1: api.admin.user.AddUserReq
	(*user.GetUserReq)(nil), // 2: api.admin.user.GetUserReq
	(*structpb.Struct)(nil), // 3: google.protobuf.Struct
	(*common.Id)(nil),       // 4: api.common.Id
	(*user.User)(nil),       // 5: api.admin.user.User
}
var file_admin_user_service_proto_depIdxs = []int32{
	0, // 0: api.admin.AdminUserService.Health:input_type -> google.protobuf.Empty
	1, // 1: api.admin.AdminUserService.AddUser:input_type -> api.admin.user.AddUserReq
	2, // 2: api.admin.AdminUserService.GetUser:input_type -> api.admin.user.GetUserReq
	3, // 3: api.admin.AdminUserService.Health:output_type -> google.protobuf.Struct
	4, // 4: api.admin.AdminUserService.AddUser:output_type -> api.common.Id
	5, // 5: api.admin.AdminUserService.GetUser:output_type -> api.admin.user.User
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_admin_user_service_proto_init() }
func file_admin_user_service_proto_init() {
	if File_admin_user_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_user_service_proto_rawDesc), len(file_admin_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_user_service_proto_goTypes,
		DependencyIndexes: file_admin_user_service_proto_depIdxs,
	}.Build()
	File_admin_user_service_proto = out.File
	file_admin_user_service_proto_goTypes = nil
	file_admin_user_service_proto_depIdxs = nil
}
