name: Golang

on:
  push:
    branches:
      - v2
  pull_request:
    branches:
      - v2

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false
      - run: make test-all
      - run: make bin-all
